# Generated by Django 5.0.2 on 2024-02-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitycampus',
            name='Campus_Id',
        ),
    ]
